jenkins:
  systemMessage: "Jenkins Configuration for CKDC Project"
  numExecutors: 2
  scmCheckoutRetryCount: 0
  mode: NORMAL
  
security:
  realm: jenkins
  authorizationStrategy:
    projectMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"

plugins:
  required:
    - id: "cloudbees-folder"
      version: "6.976.v4dc79fb_c458d"
    - id: "config-file-provider"
      version: "980.v88956a_a_5d6a_d"
    - id: "credentials"
      version: "1380.va_435002fa_924"
    - id: "nodejs"
      version: "1.6.4"
    - id: "matrix-auth"
      version: "3.2.5"
    - id: "eddsa-api"
      version: "0.3.0-4.v84c6f0f4969e"
  
tool:
  nodejs:
    installations:
    - name: "NodeJS"
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "18.18.0"

agents:
  - permanent:
      name: "agent1"
      remoteFS: "/jenkins/agent"
      launcher:
        command:
          command: "java -jar agent.jar"